### PR TITLE
fix: responsive design improvements

### PR DESCRIPTION
**Pull request by Victor-Salomon**
Fix 
- Substrate Modal mobile responsive
- Form mobile responsive

Please give it a try as my iPhone is too big to display the white border: 
https://turtle-app-git-fix-responsive-form-velocity-labs.vercel.app/

### CODE REVIEW

**Review by NunoAlexandre — APPROVED** [review]
It looks great on my iPhone xs 🙌🏻

**Review by noahjoeris — APPROVED** [review]
Suuuuper great 🚀

**Comment by noahjoeris** [comment]
Btw you can simulate phone screens on the developer console in the browser 😄

**Comment by Victor-Salomon** [comment]
Thanks guys! 🦾

Yeah, I know for the mobile version from the computer browser. But I always find out a way to properly test it when possible. In case 😅

**Pull request merged**
