### PR TITLE
feat: seo improvements

### PR DESCRIPTION
**Pull request by Victor-Salomon**
Add all the missing SEO files, images, manifests. 

It's the first time I'm implementing this and I'm not an expert in these SEO files/tag.
I have based this PR on the official Next Js documentation & some articles I've read. 

Open to discussion

### CODE REVIEW

**Comment by noahjoeris** [comment]
Crazy I have never seen most of the settings before 😅  But I trust your research.
But I always thought nextjs already handles SEO mostly for you no?

**Comment by noahjoeris** [comment]
And the app/public/android-chrome-512x512.png is 2.14MB large. Can we get it smaller?

**Comment by Victor-Salomon** [comment]
I was aware of some parts of this but I was impressed about "all" that needed to be added. 
Next JS optimises many SEO things for us yes. These are more like Browsers crawling 'requirements'.

Let me check this large image. I've compressed everything so I'm surprised this one is still that heavy.

**Review by noahjoeris — APPROVED** [review]
Nice 👏

**Comment by NunoAlexandre** [comment]
> I was aware of some parts of this but I was impressed about "all" that needed to be added. Next JS optimises many SEO things for us yes. These are more like Browsers crawling 'requirements'.
> 
> Let me check this large image. I've compressed everything so I'm surprised this one is still that heavy.

@Victor-Salomon [tinypng](https://tinypng.com/) is a really nice site to compress png shall you need one :)

**Pull request merged**
