### PR TITLE
deps: Dedupe and update

### PR DESCRIPTION
**Pull request by NunoAlexandre**
I was trying to fix some duplicate dependency issues but it's not going anywhere. Just leaving here the `pnpm dedupe` and `pnpm update` changes that add a tiny bit of benefit anyways.

### CODE REVIEW

**Comment by NunoAlexandre** [comment]
@noahjoeris @Victor-Salomon this is ready for review even tho that there are no manual changes here 👍

**Review by noahjoeris — APPROVED** [review]
As long as the app still works this is fine 😄 👍

**Review by Victor-Salomon — APPROVED** [review]
Not tested locally but it looks good on paper :)

**Comment by Victor-Salomon** [comment]
@NunoAlexandre can we integrate this off topic to your PR? 
 
 remove the following log in useFees() hook (to avoid doing another PR against main branch later?)
console.log('Token id to coingeko', tokenCoingeckoId)

image

**Pull request merged**
